set -x
src/common/runtest.exe -w '' src/functional/argv.exe >src/functional/argv.err || true
src/common/runtest.exe -w '' src/functional/basename.exe >src/functional/basename.err || true
src/common/runtest.exe -w '' src/functional/clocale_mbfuncs.exe >src/functional/clocale_mbfuncs.err || true
src/common/runtest.exe -w '' src/functional/clock_gettime.exe >src/functional/clock_gettime.err || true
src/common/runtest.exe -w '' src/functional/crypt.exe >src/functional/crypt.err || true
src/common/runtest.exe -w '' src/functional/dirname.exe >src/functional/dirname.err || true
src/common/runtest.exe -w '' src/functional/dlopen.exe >src/functional/dlopen.err || true
src/common/runtest.exe -w '' src/functional/env.exe >src/functional/env.err || true
src/common/runtest.exe -w '' src/functional/fcntl.exe >src/functional/fcntl.err || true
src/common/runtest.exe -w '' src/functional/fdopen.exe >src/functional/fdopen.err || true
src/common/runtest.exe -w '' src/functional/fnmatch.exe >src/functional/fnmatch.err || true
src/common/runtest.exe -w '' src/functional/fscanf.exe >src/functional/fscanf.err || true
src/common/runtest.exe -w '' src/functional/fwscanf.exe >src/functional/fwscanf.err || true
src/common/runtest.exe -w '' src/functional/iconv_open.exe >src/functional/iconv_open.err || true
src/common/runtest.exe -w '' src/functional/inet_pton.exe >src/functional/inet_pton.err || true
src/common/runtest.exe -w '' src/functional/ipc_msg.exe >src/functional/ipc_msg.err || true
src/common/runtest.exe -w '' src/functional/ipc_sem.exe >src/functional/ipc_sem.err || true
src/common/runtest.exe -w '' src/functional/ipc_shm.exe >src/functional/ipc_shm.err || true
src/common/runtest.exe -w '' src/functional/mbc.exe >src/functional/mbc.err || true
src/common/runtest.exe -w '' src/functional/memstream.exe >src/functional/memstream.err || true
src/common/runtest.exe -w '' src/functional/popen.exe >src/functional/popen.err || true
src/common/runtest.exe -w '' src/functional/pthread_cancel-points.exe >src/functional/pthread_cancel-points.err || true
src/common/runtest.exe -w '' src/functional/pthread_cancel.exe >src/functional/pthread_cancel.err || true
src/common/runtest.exe -w '' src/functional/pthread_cond.exe >src/functional/pthread_cond.err || true
src/common/runtest.exe -w '' src/functional/pthread_mutex.exe >src/functional/pthread_mutex.err || true
src/common/runtest.exe -w '' src/functional/pthread_mutex_pi.exe >src/functional/pthread_mutex_pi.err || true
src/common/runtest.exe -w '' src/functional/pthread_robust.exe >src/functional/pthread_robust.err || true
src/common/runtest.exe -w '' src/functional/pthread_tsd.exe >src/functional/pthread_tsd.err || true
src/common/runtest.exe -w '' src/functional/qsort.exe >src/functional/qsort.err || true
src/common/runtest.exe -w '' src/functional/random.exe >src/functional/random.err || true
src/common/runtest.exe -w '' src/functional/search_hsearch.exe >src/functional/search_hsearch.err || true
src/common/runtest.exe -w '' src/functional/search_insque.exe >src/functional/search_insque.err || true
src/common/runtest.exe -w '' src/functional/search_lsearch.exe >src/functional/search_lsearch.err || true
src/common/runtest.exe -w '' src/functional/search_tsearch.exe >src/functional/search_tsearch.err || true
src/common/runtest.exe -w '' src/functional/sem_init.exe >src/functional/sem_init.err || true
src/common/runtest.exe -w '' src/functional/sem_open.exe >src/functional/sem_open.err || true
src/common/runtest.exe -w '' src/functional/setjmp.exe >src/functional/setjmp.err || true
src/common/runtest.exe -w '' src/functional/snprintf.exe >src/functional/snprintf.err || true
src/common/runtest.exe -w '' src/functional/socket.exe >src/functional/socket.err || true
src/common/runtest.exe -w '' src/functional/spawn.exe >src/functional/spawn.err || true
src/common/runtest.exe -w '' src/functional/sscanf.exe >src/functional/sscanf.err || true
src/common/runtest.exe -w '' src/functional/sscanf_long.exe >src/functional/sscanf_long.err || true
src/common/runtest.exe -w '' src/functional/stat.exe >src/functional/stat.err || true
src/common/runtest.exe -w '' src/functional/strftime.exe >src/functional/strftime.err || true
src/common/runtest.exe -w '' src/functional/string.exe >src/functional/string.err || true
src/common/runtest.exe -w '' src/functional/string_memcpy.exe >src/functional/string_memcpy.err || true
src/common/runtest.exe -w '' src/functional/string_memmem.exe >src/functional/string_memmem.err || true
src/common/runtest.exe -w '' src/functional/string_memset.exe >src/functional/string_memset.err || true
src/common/runtest.exe -w '' src/functional/string_strchr.exe >src/functional/string_strchr.err || true
src/common/runtest.exe -w '' src/functional/string_strcspn.exe >src/functional/string_strcspn.err || true
src/common/runtest.exe -w '' src/functional/string_strstr.exe >src/functional/string_strstr.err || true
src/common/runtest.exe -w '' src/functional/strptime.exe >src/functional/strptime.err || true
src/common/runtest.exe -w '' src/functional/strtod.exe >src/functional/strtod.err || true
src/common/runtest.exe -w '' src/functional/strtod_long.exe >src/functional/strtod_long.err || true
src/common/runtest.exe -w '' src/functional/strtod_simple.exe >src/functional/strtod_simple.err || true
src/common/runtest.exe -w '' src/functional/strtof.exe >src/functional/strtof.err || true
src/common/runtest.exe -w '' src/functional/strtol.exe >src/functional/strtol.err || true
src/common/runtest.exe -w '' src/functional/strtold.exe >src/functional/strtold.err || true
src/common/runtest.exe -w '' src/functional/swprintf.exe >src/functional/swprintf.err || true
src/common/runtest.exe -w '' src/functional/tgmath.exe >src/functional/tgmath.err || true
src/common/runtest.exe -w '' src/functional/time.exe >src/functional/time.err || true

src/common/runtest.exe -w '' src/functional/tls_align_dlopen.exe >src/functional/tls_align_dlopen.err || true
src/common/runtest.exe -w '' src/functional/tls_init.exe >src/functional/tls_init.err || true
src/common/runtest.exe -w '' src/functional/tls_init_dlopen.exe >src/functional/tls_init_dlopen.err || true
src/common/runtest.exe -w '' src/functional/tls_local_exec.exe >src/functional/tls_local_exec.err || true
src/common/runtest.exe -w '' src/functional/udiv.exe >src/functional/udiv.err || true
src/common/runtest.exe -w '' src/functional/ungetc.exe >src/functional/ungetc.err || true
src/common/runtest.exe -w '' src/functional/utime.exe >src/functional/utime.err || true
src/common/runtest.exe -w '' src/functional/vfork.exe >src/functional/vfork.err || true
BUILDERROR src/api/main.exe
src/common/runtest.exe -w '' src/functional/wcsstr.exe >src/functional/wcsstr.err || true
src/common/runtest.exe -w '' src/functional/wcstol.exe >src/functional/wcstol.err || true
src/common/runtest.exe -w '' src/math/acos.exe >src/math/acos.err || true
src/common/runtest.exe -w '' src/math/acosf.exe >src/math/acosf.err || true
src/common/runtest.exe -w '' src/math/acosh.exe >src/math/acosh.err || true
src/common/runtest.exe -w '' src/math/acoshf.exe >src/math/acoshf.err || true

src/common/runtest.exe -w '' src/math/acoshl.exe >src/math/acoshl.err || true
src/common/runtest.exe -w '' src/math/acosl.exe >src/math/acosl.err || true
src/common/runtest.exe -w '' src/math/asin.exe >src/math/asin.err || true
src/common/runtest.exe -w '' src/math/asinf.exe >src/math/asinf.err || true
src/common/runtest.exe -w '' src/math/asinh.exe >src/math/asinh.err || true
src/common/runtest.exe -w '' src/math/asinhf.exe >src/math/asinhf.err || true
src/common/runtest.exe -w '' src/math/asinhl.exe >src/math/asinhl.err || true
src/common/runtest.exe -w '' src/math/asinl.exe >src/math/asinl.err || true
src/common/runtest.exe -w '' src/math/atan.exe >src/math/atan.err || true
src/common/runtest.exe -w '' src/math/atan2.exe >src/math/atan2.err || true
src/common/runtest.exe -w '' src/math/atan2f.exe >src/math/atan2f.err || true
src/common/runtest.exe -w '' src/math/atan2l.exe >src/math/atan2l.err || true
src/common/runtest.exe -w '' src/math/atanf.exe >src/math/atanf.err || true
src/common/runtest.exe -w '' src/math/atanh.exe >src/math/atanh.err || true
src/common/runtest.exe -w '' src/math/atanhf.exe >src/math/atanhf.err || true
src/common/runtest.exe -w '' src/math/atanhl.exe >src/math/atanhl.err || true
src/common/runtest.exe -w '' src/math/atanl.exe >src/math/atanl.err || true
src/common/runtest.exe -w '' src/math/cbrt.exe >src/math/cbrt.err || true
src/common/runtest.exe -w '' src/math/cbrtf.exe >src/math/cbrtf.err || true
src/common/runtest.exe -w '' src/math/cbrtl.exe >src/math/cbrtl.err || true
src/common/runtest.exe -w '' src/math/ceil.exe >src/math/ceil.err || true
src/common/runtest.exe -w '' src/math/ceilf.exe >src/math/ceilf.err || true
src/common/runtest.exe -w '' src/math/ceill.exe >src/math/ceill.err || true
src/common/runtest.exe -w '' src/math/copysign.exe >src/math/copysign.err || true
src/common/runtest.exe -w '' src/math/copysignf.exe >src/math/copysignf.err || true
src/common/runtest.exe -w '' src/math/copysignl.exe >src/math/copysignl.err || true
src/common/runtest.exe -w '' src/math/cos.exe >src/math/cos.err || true
src/common/runtest.exe -w '' src/math/cosf.exe >src/math/cosf.err || true
src/common/runtest.exe -w '' src/math/cosh.exe >src/math/cosh.err || true
src/common/runtest.exe -w '' src/math/coshf.exe >src/math/coshf.err || true
src/common/runtest.exe -w '' src/math/coshl.exe >src/math/coshl.err || true
src/common/runtest.exe -w '' src/math/cosl.exe >src/math/cosl.err || true
src/common/runtest.exe -w '' src/math/drem.exe >src/math/drem.err || true
src/common/runtest.exe -w '' src/math/dremf.exe >src/math/dremf.err || true
src/common/runtest.exe -w '' src/math/erf.exe >src/math/erf.err || true
src/common/runtest.exe -w '' src/math/erfc.exe >src/math/erfc.err || true
src/common/runtest.exe -w '' src/math/erfcf.exe >src/math/erfcf.err || true
src/common/runtest.exe -w '' src/math/erfcl.exe >src/math/erfcl.err || true
src/common/runtest.exe -w '' src/math/erff.exe >src/math/erff.err || true
src/common/runtest.exe -w '' src/math/erfl.exe >src/math/erfl.err || true
src/common/runtest.exe -w '' src/math/exp.exe >src/math/exp.err || true
src/common/runtest.exe -w '' src/math/exp10.exe >src/math/exp10.err || true
src/common/runtest.exe -w '' src/math/exp10f.exe >src/math/exp10f.err || true
src/common/runtest.exe -w '' src/math/exp10l.exe >src/math/exp10l.err || true
src/common/runtest.exe -w '' src/math/exp2.exe >src/math/exp2.err || true
src/common/runtest.exe -w '' src/math/exp2f.exe >src/math/exp2f.err || true
src/common/runtest.exe -w '' src/math/exp2l.exe >src/math/exp2l.err || true
src/common/runtest.exe -w '' src/math/expf.exe >src/math/expf.err || true
src/common/runtest.exe -w '' src/math/expl.exe >src/math/expl.err || true
src/common/runtest.exe -w '' src/math/expm1.exe >src/math/expm1.err || true
src/common/runtest.exe -w '' src/math/expm1f.exe >src/math/expm1f.err || true
src/common/runtest.exe -w '' src/math/expm1l.exe >src/math/expm1l.err || true
src/common/runtest.exe -w '' src/math/fabs.exe >src/math/fabs.err || true
src/common/runtest.exe -w '' src/math/fabsf.exe >src/math/fabsf.err || true
src/common/runtest.exe -w '' src/math/fabsl.exe >src/math/fabsl.err || true
src/common/runtest.exe -w '' src/math/fdim.exe >src/math/fdim.err || true
src/common/runtest.exe -w '' src/math/fdimf.exe >src/math/fdimf.err || true
src/common/runtest.exe -w '' src/math/fdiml.exe >src/math/fdiml.err || true
src/common/runtest.exe -w '' src/math/fenv.exe >src/math/fenv.err || true
src/common/runtest.exe -w '' src/math/floor.exe >src/math/floor.err || true
src/common/runtest.exe -w '' src/math/floorf.exe >src/math/floorf.err || true
src/common/runtest.exe -w '' src/math/floorl.exe >src/math/floorl.err || true
src/common/runtest.exe -w '' src/math/fma.exe >src/math/fma.err || true
src/common/runtest.exe -w '' src/math/fmaf.exe >src/math/fmaf.err || true
src/common/runtest.exe -w '' src/math/fmal.exe >src/math/fmal.err || true
src/common/runtest.exe -w '' src/math/fmax.exe >src/math/fmax.err || true
src/common/runtest.exe -w '' src/math/fmaxf.exe >src/math/fmaxf.err || true
src/common/runtest.exe -w '' src/math/fmaxl.exe >src/math/fmaxl.err || true
src/common/runtest.exe -w '' src/math/fmin.exe >src/math/fmin.err || true
src/common/runtest.exe -w '' src/math/fminf.exe >src/math/fminf.err || true
src/common/runtest.exe -w '' src/math/fminl.exe >src/math/fminl.err || true
src/common/runtest.exe -w '' src/math/fmod.exe >src/math/fmod.err || true
src/common/runtest.exe -w '' src/math/fmodf.exe >src/math/fmodf.err || true
src/common/runtest.exe -w '' src/math/fmodl.exe >src/math/fmodl.err || true
src/common/runtest.exe -w '' src/math/fpclassify.exe >src/math/fpclassify.err || true
src/common/runtest.exe -w '' src/math/frexp.exe >src/math/frexp.err || true
src/common/runtest.exe -w '' src/math/frexpf.exe >src/math/frexpf.err || true
src/common/runtest.exe -w '' src/math/frexpl.exe >src/math/frexpl.err || true
src/common/runtest.exe -w '' src/math/hypot.exe >src/math/hypot.err || true
src/common/runtest.exe -w '' src/math/hypotf.exe >src/math/hypotf.err || true
src/common/runtest.exe -w '' src/math/hypotl.exe >src/math/hypotl.err || true
src/common/runtest.exe -w '' src/math/ilogb.exe >src/math/ilogb.err || true
src/common/runtest.exe -w '' src/math/ilogbf.exe >src/math/ilogbf.err || true
src/common/runtest.exe -w '' src/math/ilogbl.exe >src/math/ilogbl.err || true
src/common/runtest.exe -w '' src/math/isless.exe >src/math/isless.err || true
src/common/runtest.exe -w '' src/math/j0.exe >src/math/j0.err || true
src/common/runtest.exe -w '' src/math/j0f.exe >src/math/j0f.err || true
src/common/runtest.exe -w '' src/math/j1.exe >src/math/j1.err || true
src/common/runtest.exe -w '' src/math/j1f.exe >src/math/j1f.err || true
src/common/runtest.exe -w '' src/math/jn.exe >src/math/jn.err || true
src/common/runtest.exe -w '' src/math/jnf.exe >src/math/jnf.err || true
src/common/runtest.exe -w '' src/math/ldexp.exe >src/math/ldexp.err || true
src/common/runtest.exe -w '' src/math/ldexpf.exe >src/math/ldexpf.err || true
src/common/runtest.exe -w '' src/math/ldexpl.exe >src/math/ldexpl.err || true
src/common/runtest.exe -w '' src/math/lgamma.exe >src/math/lgamma.err || true
src/common/runtest.exe -w '' src/math/lgamma_r.exe >src/math/lgamma_r.err || true
src/common/runtest.exe -w '' src/math/lgammaf.exe >src/math/lgammaf.err || true
src/common/runtest.exe -w '' src/math/lgammaf_r.exe >src/math/lgammaf_r.err || true
src/common/runtest.exe -w '' src/math/lgammal.exe >src/math/lgammal.err || true
src/common/runtest.exe -w '' src/math/lgammal_r.exe >src/math/lgammal_r.err || true
src/common/runtest.exe -w '' src/math/llrint.exe >src/math/llrint.err || true
src/common/runtest.exe -w '' src/math/llrintf.exe >src/math/llrintf.err || true
src/common/runtest.exe -w '' src/math/llrintl.exe >src/math/llrintl.err || true
src/common/runtest.exe -w '' src/math/llround.exe >src/math/llround.err || true
src/common/runtest.exe -w '' src/math/llroundf.exe >src/math/llroundf.err || true
src/common/runtest.exe -w '' src/math/llroundl.exe >src/math/llroundl.err || true
src/common/runtest.exe -w '' src/math/log.exe >src/math/log.err || true
src/common/runtest.exe -w '' src/math/log10.exe >src/math/log10.err || true
src/common/runtest.exe -w '' src/math/log10f.exe >src/math/log10f.err || true
src/common/runtest.exe -w '' src/math/log10l.exe >src/math/log10l.err || true
src/common/runtest.exe -w '' src/math/log1p.exe >src/math/log1p.err || true
src/common/runtest.exe -w '' src/math/log1pf.exe >src/math/log1pf.err || true
src/common/runtest.exe -w '' src/math/log1pl.exe >src/math/log1pl.err || true
src/common/runtest.exe -w '' src/math/log2.exe >src/math/log2.err || true
src/common/runtest.exe -w '' src/math/log2f.exe >src/math/log2f.err || true
src/common/runtest.exe -w '' src/math/log2l.exe >src/math/log2l.err || true
src/common/runtest.exe -w '' src/math/logb.exe >src/math/logb.err || true
src/common/runtest.exe -w '' src/math/logbf.exe >src/math/logbf.err || true
src/common/runtest.exe -w '' src/math/logbl.exe >src/math/logbl.err || true
src/common/runtest.exe -w '' src/math/logf.exe >src/math/logf.err || true
src/common/runtest.exe -w '' src/math/logl.exe >src/math/logl.err || true
src/common/runtest.exe -w '' src/math/lrint.exe >src/math/lrint.err || true
src/common/runtest.exe -w '' src/math/lrintf.exe >src/math/lrintf.err || true
src/common/runtest.exe -w '' src/math/lrintl.exe >src/math/lrintl.err || true
src/common/runtest.exe -w '' src/math/lround.exe >src/math/lround.err || true
src/common/runtest.exe -w '' src/math/lroundf.exe >src/math/lroundf.err || true
src/common/runtest.exe -w '' src/math/lroundl.exe >src/math/lroundl.err || true
src/common/runtest.exe -w '' src/math/modf.exe >src/math/modf.err || true
src/common/runtest.exe -w '' src/math/modff.exe >src/math/modff.err || true
src/common/runtest.exe -w '' src/math/modfl.exe >src/math/modfl.err || true
src/common/runtest.exe -w '' src/math/nearbyint.exe >src/math/nearbyint.err || true
src/common/runtest.exe -w '' src/math/nearbyintf.exe >src/math/nearbyintf.err || true
src/common/runtest.exe -w '' src/math/nearbyintl.exe >src/math/nearbyintl.err || true
src/common/runtest.exe -w '' src/math/nextafter.exe >src/math/nextafter.err || true
src/common/runtest.exe -w '' src/math/nextafterf.exe >src/math/nextafterf.err || true
src/common/runtest.exe -w '' src/math/nextafterl.exe >src/math/nextafterl.err || true
src/common/runtest.exe -w '' src/math/nexttoward.exe >src/math/nexttoward.err || true
src/common/runtest.exe -w '' src/math/nexttowardf.exe >src/math/nexttowardf.err || true
src/common/runtest.exe -w '' src/math/nexttowardl.exe >src/math/nexttowardl.err || true
src/common/runtest.exe -w '' src/math/pow.exe >src/math/pow.err || true
src/common/runtest.exe -w '' src/math/pow10.exe >src/math/pow10.err || true
src/common/runtest.exe -w '' src/math/pow10f.exe >src/math/pow10f.err || true
src/common/runtest.exe -w '' src/math/pow10l.exe >src/math/pow10l.err || true
src/common/runtest.exe -w '' src/math/powf.exe >src/math/powf.err || true
src/common/runtest.exe -w '' src/math/powl.exe >src/math/powl.err || true
src/common/runtest.exe -w '' src/math/remainder.exe >src/math/remainder.err || true
src/common/runtest.exe -w '' src/math/remainderf.exe >src/math/remainderf.err || true
src/common/runtest.exe -w '' src/math/remainderl.exe >src/math/remainderl.err || true
src/common/runtest.exe -w '' src/math/remquo.exe >src/math/remquo.err || true
src/common/runtest.exe -w '' src/math/remquof.exe >src/math/remquof.err || true
src/common/runtest.exe -w '' src/math/remquol.exe >src/math/remquol.err || true
src/common/runtest.exe -w '' src/math/rint.exe >src/math/rint.err || true
src/common/runtest.exe -w '' src/math/rintf.exe >src/math/rintf.err || true
src/common/runtest.exe -w '' src/math/rintl.exe >src/math/rintl.err || true
src/common/runtest.exe -w '' src/math/round.exe >src/math/round.err || true
src/common/runtest.exe -w '' src/math/roundf.exe >src/math/roundf.err || true
src/common/runtest.exe -w '' src/math/roundl.exe >src/math/roundl.err || true
src/common/runtest.exe -w '' src/math/scalb.exe >src/math/scalb.err || true
src/common/runtest.exe -w '' src/math/scalbf.exe >src/math/scalbf.err || true
src/common/runtest.exe -w '' src/math/scalbln.exe >src/math/scalbln.err || true
src/common/runtest.exe -w '' src/math/scalblnf.exe >src/math/scalblnf.err || true
src/common/runtest.exe -w '' src/math/scalblnl.exe >src/math/scalblnl.err || true
src/common/runtest.exe -w '' src/math/scalbn.exe >src/math/scalbn.err || true
src/common/runtest.exe -w '' src/math/scalbnf.exe >src/math/scalbnf.err || true
src/common/runtest.exe -w '' src/math/scalbnl.exe >src/math/scalbnl.err || true
src/common/runtest.exe -w '' src/math/sin.exe >src/math/sin.err || true
src/common/runtest.exe -w '' src/math/sincos.exe >src/math/sincos.err || true
src/common/runtest.exe -w '' src/math/sincosf.exe >src/math/sincosf.err || true
src/common/runtest.exe -w '' src/math/sincosl.exe >src/math/sincosl.err || true
src/common/runtest.exe -w '' src/math/sinf.exe >src/math/sinf.err || true
src/common/runtest.exe -w '' src/math/sinh.exe >src/math/sinh.err || true
src/common/runtest.exe -w '' src/math/sinhf.exe >src/math/sinhf.err || true
src/common/runtest.exe -w '' src/math/sinhl.exe >src/math/sinhl.err || true
src/common/runtest.exe -w '' src/math/sinl.exe >src/math/sinl.err || true
src/common/runtest.exe -w '' src/math/sqrt.exe >src/math/sqrt.err || true
src/common/runtest.exe -w '' src/math/sqrtf.exe >src/math/sqrtf.err || true
src/common/runtest.exe -w '' src/math/sqrtl.exe >src/math/sqrtl.err || true
src/common/runtest.exe -w '' src/math/tan.exe >src/math/tan.err || true
src/common/runtest.exe -w '' src/math/tanf.exe >src/math/tanf.err || true
src/common/runtest.exe -w '' src/math/tanh.exe >src/math/tanh.err || true
src/common/runtest.exe -w '' src/math/tanhf.exe >src/math/tanhf.err || true
src/common/runtest.exe -w '' src/math/tanhl.exe >src/math/tanhl.err || true
src/common/runtest.exe -w '' src/math/tanl.exe >src/math/tanl.err || true
src/common/runtest.exe -w '' src/math/tgamma.exe >src/math/tgamma.err || true
src/common/runtest.exe -w '' src/math/tgammaf.exe >src/math/tgammaf.err || true
src/common/runtest.exe -w '' src/math/tgammal.exe >src/math/tgammal.err || true
src/common/runtest.exe -w '' src/math/trunc.exe >src/math/trunc.err || true
src/common/runtest.exe -w '' src/math/truncf.exe >src/math/truncf.err || true
src/common/runtest.exe -w '' src/math/truncl.exe >src/math/truncl.err || true
src/common/runtest.exe -w '' src/math/y0.exe >src/math/y0.err || true
src/common/runtest.exe -w '' src/math/y0f.exe >src/math/y0f.err || true
src/common/runtest.exe -w '' src/math/y1.exe >src/math/y1.err || true
src/common/runtest.exe -w '' src/math/y1f.exe >src/math/y1f.err || true
src/common/runtest.exe -w '' src/math/yn.exe >src/math/yn.err || true
src/common/runtest.exe -w '' src/math/ynf.exe >src/math/ynf.err || true
src/common/runtest.exe -w '' src/musl/pleval-static.exe >src/musl/pleval-static.err || true
src/common/runtest.exe -w '' src/regression/daemon-failure.exe >src/regression/daemon-failure.err || true
src/common/runtest.exe -w '' src/regression/dn_expand-empty.exe >src/regression/dn_expand-empty.err || true
src/common/runtest.exe -w '' src/regression/dn_expand-ptr-0.exe >src/regression/dn_expand-ptr-0.err || true
src/common/runtest.exe -w '' src/regression/execle-env.exe >src/regression/execle-env.err || true
src/common/runtest.exe -w '' src/regression/fflush-exit.exe >src/regression/fflush-exit.err || true
src/common/runtest.exe -w '' src/regression/fgets-eof.exe >src/regression/fgets-eof.err || true
src/common/runtest.exe -w '' src/regression/fgetwc-buffering.exe >src/regression/fgetwc-buffering.err || true
src/common/runtest.exe -w '' src/regression/flockfile-list.exe >src/regression/flockfile-list.err || true
src/common/runtest.exe -w '' src/regression/fpclassify-invalid-ld80.exe >src/regression/fpclassify-invalid-ld80.err || true
src/common/runtest.exe -w '' src/regression/ftello-unflushed-append.exe >src/regression/ftello-unflushed-append.err || true
src/common/runtest.exe -w '' src/regression/getpwnam_r-crash.exe >src/regression/getpwnam_r-crash.err || true
src/common/runtest.exe -w '' src/regression/getpwnam_r-errno.exe >src/regression/getpwnam_r-errno.err || true
src/common/runtest.exe -w '' src/regression/iconv-roundtrips.exe >src/regression/iconv-roundtrips.err || true
src/common/runtest.exe -w '' src/regression/inet_ntop-v4mapped.exe >src/regression/inet_ntop-v4mapped.err || true
src/common/runtest.exe -w '' src/regression/inet_pton-empty-last-field.exe >src/regression/inet_pton-empty-last-field.err || true
src/common/runtest.exe -w '' src/regression/iswspace-null.exe >src/regression/iswspace-null.err || true
src/common/runtest.exe -w '' src/regression/lrand48-signextend.exe >src/regression/lrand48-signextend.err || true
src/common/runtest.exe -w '' src/regression/lseek-large.exe >src/regression/lseek-large.err || true
src/common/runtest.exe -w '' src/regression/malloc-0.exe >src/regression/malloc-0.err || true
src/common/runtest.exe -w '' src/regression/malloc-brk-fail.exe >src/regression/malloc-brk-fail.err || true
src/common/runtest.exe -w '' src/regression/malloc-oom.exe >src/regression/malloc-oom.err || true
src/common/runtest.exe -w '' src/regression/mbsrtowcs-overflow.exe >src/regression/mbsrtowcs-overflow.err || true
src/common/runtest.exe -w '' src/regression/memmem-oob-read.exe >src/regression/memmem-oob-read.err || true
src/common/runtest.exe -w '' src/regression/memmem-oob.exe >src/regression/memmem-oob.err || true
src/common/runtest.exe -w '' src/regression/mkdtemp-failure.exe >src/regression/mkdtemp-failure.err || true
src/common/runtest.exe -w '' src/regression/mkstemp-failure.exe >src/regression/mkstemp-failure.err || true
src/common/runtest.exe -w '' src/regression/printf-1e9-oob.exe >src/regression/printf-1e9-oob.err || true
src/common/runtest.exe -w '' src/regression/printf-fmt-g-round.exe >src/regression/printf-fmt-g-round.err || true
src/common/runtest.exe -w '' src/regression/printf-fmt-g-zeros.exe >src/regression/printf-fmt-g-zeros.err || true
src/common/runtest.exe -w '' src/regression/printf-fmt-n.exe >src/regression/printf-fmt-n.err || true
src/common/runtest.exe -w '' src/regression/pthread-robust-detach.exe >src/regression/pthread-robust-detach.err || true
src/common/runtest.exe -w '' src/regression/pthread_atfork-errno-clobber.exe >src/regression/pthread_atfork-errno-clobber.err || true
src/common/runtest.exe -w '' src/regression/pthread_cancel-sem_wait.exe >src/regression/pthread_cancel-sem_wait.err || true
src/common/runtest.exe -w '' src/regression/pthread_cond-smasher.exe >src/regression/pthread_cond-smasher.err || true
src/common/runtest.exe -w '' src/regression/pthread_cond_wait-cancel_ignored.exe >src/regression/pthread_cond_wait-cancel_ignored.err || true
src/common/runtest.exe -w '' src/regression/pthread_condattr_setclock.exe >src/regression/pthread_condattr_setclock.err || true
src/common/runtest.exe -w '' src/regression/pthread_create-oom.exe >src/regression/pthread_create-oom.err || true
src/common/runtest.exe -w '' src/regression/pthread_exit-cancel.exe >src/regression/pthread_exit-cancel.err || true
src/common/runtest.exe -w '' src/regression/pthread_exit-dtor.exe >src/regression/pthread_exit-dtor.err || true
src/common/runtest.exe -w '' src/regression/pthread_once-deadlock.exe >src/regression/pthread_once-deadlock.err || true
src/common/runtest.exe -w '' src/regression/pthread_rwlock-ebusy.exe >src/regression/pthread_rwlock-ebusy.err || true
src/common/runtest.exe -w '' src/regression/putenv-doublefree.exe >src/regression/putenv-doublefree.err || true
src/common/runtest.exe -w '' src/regression/raise-race.exe >src/regression/raise-race.err || true
src/common/runtest.exe -w '' src/regression/regex-backref-0.exe >src/regression/regex-backref-0.err || true
src/common/runtest.exe -w '' src/regression/regex-bracket-icase.exe >src/regression/regex-bracket-icase.err || true
src/common/runtest.exe -w '' src/regression/regex-ere-backref.exe >src/regression/regex-ere-backref.err || true
src/common/runtest.exe -w '' src/regression/regex-escaped-high-byte.exe >src/regression/regex-escaped-high-byte.err || true
src/common/runtest.exe -w '' src/regression/regex-negated-range.exe >src/regression/regex-negated-range.err || true
src/common/runtest.exe -w '' src/regression/regexec-nosub.exe >src/regression/regexec-nosub.err || true
src/common/runtest.exe -w '' src/regression/rewind-clear-error.exe >src/regression/rewind-clear-error.err || true
src/common/runtest.exe -w '' src/regression/rlimit-open-files.exe >src/regression/rlimit-open-files.err || true
src/common/runtest.exe -w '' src/regression/scanf-bytes-consumed.exe >src/regression/scanf-bytes-consumed.err || true
src/common/runtest.exe -w '' src/regression/scanf-match-literal-eof.exe >src/regression/scanf-match-literal-eof.err || true
src/common/runtest.exe -w '' src/regression/scanf-nullbyte-char.exe >src/regression/scanf-nullbyte-char.err || true
src/common/runtest.exe -w '' src/regression/setenv-oom.exe >src/regression/setenv-oom.err || true
src/common/runtest.exe -w '' src/regression/setvbuf-unget.exe >src/regression/setvbuf-unget.err || true
src/common/runtest.exe -w '' src/regression/sigaltstack.exe >src/regression/sigaltstack.err || true
src/common/runtest.exe -w '' src/regression/sigprocmask-internal.exe >src/regression/sigprocmask-internal.err || true
src/common/runtest.exe -w '' src/regression/sigreturn.exe >src/regression/sigreturn.err || true
src/common/runtest.exe -w '' src/regression/sscanf-eof.exe >src/regression/sscanf-eof.err || true
src/common/runtest.exe -w '' src/regression/statvfs.exe >src/regression/statvfs.err || true
src/common/runtest.exe -w '' src/regression/strverscmp.exe >src/regression/strverscmp.err || true
src/common/runtest.exe -w '' src/regression/syscall-sign-extend.exe >src/regression/syscall-sign-extend.err || true
src/common/runtest.exe -w '' src/regression/tls_get_new-dtv.exe >src/regression/tls_get_new-dtv.err || true
src/common/runtest.exe -w '' src/regression/uselocale-0.exe >src/regression/uselocale-0.err || true
src/common/runtest.exe -w '' src/regression/wcsncpy-read-overflow.exe >src/regression/wcsncpy-read-overflow.err || true
src/common/runtest.exe -w '' src/regression/wcsstr-false-negative.exe >src/regression/wcsstr-false-negative.err || true
src/common/runtest.exe -w '' src/api/main.exe >src/api/main.err || true
src/common/runtest.exe -w '' src/functional/argv-static.exe >src/functional/argv-static.err || true
src/common/runtest.exe -w '' src/functional/basename-static.exe >src/functional/basename-static.err || true
src/common/runtest.exe -w '' src/functional/clocale_mbfuncs-static.exe >src/functional/clocale_mbfuncs-static.err || true
src/common/runtest.exe -w '' src/functional/clock_gettime-static.exe >src/functional/clock_gettime-static.err || true
src/common/runtest.exe -w '' src/functional/crypt-static.exe >src/functional/crypt-static.err || true
src/common/runtest.exe -w '' src/functional/dirname-static.exe >src/functional/dirname-static.err || true
src/common/runtest.exe -w '' src/functional/env-static.exe >src/functional/env-static.err || true
src/common/runtest.exe -w '' src/functional/fcntl-static.exe >src/functional/fcntl-static.err || true
src/common/runtest.exe -w '' src/functional/fdopen-static.exe >src/functional/fdopen-static.err || true
src/common/runtest.exe -w '' src/functional/fnmatch-static.exe >src/functional/fnmatch-static.err || true
src/common/runtest.exe -w '' src/functional/fscanf-static.exe >src/functional/fscanf-static.err || true
src/common/runtest.exe -w '' src/functional/fwscanf-static.exe >src/functional/fwscanf-static.err || true
src/common/runtest.exe -w '' src/functional/iconv_open-static.exe >src/functional/iconv_open-static.err || true
src/common/runtest.exe -w '' src/functional/inet_pton-static.exe >src/functional/inet_pton-static.err || true
src/common/runtest.exe -w '' src/functional/ipc_msg-static.exe >src/functional/ipc_msg-static.err || true
src/common/runtest.exe -w '' src/functional/ipc_sem-static.exe >src/functional/ipc_sem-static.err || true
src/common/runtest.exe -w '' src/functional/ipc_shm-static.exe >src/functional/ipc_shm-static.err || true
src/common/runtest.exe -w '' src/functional/mbc-static.exe >src/functional/mbc-static.err || true
src/common/runtest.exe -w '' src/functional/memstream-static.exe >src/functional/memstream-static.err || true
src/common/runtest.exe -w '' src/functional/popen-static.exe >src/functional/popen-static.err || true
src/common/runtest.exe -w '' src/functional/pthread_cancel-points-static.exe >src/functional/pthread_cancel-points-static.err || true
src/common/runtest.exe -w '' src/functional/pthread_cancel-static.exe >src/functional/pthread_cancel-static.err || true
src/common/runtest.exe -w '' src/functional/pthread_cond-static.exe >src/functional/pthread_cond-static.err || true
src/common/runtest.exe -w '' src/functional/pthread_mutex-static.exe >src/functional/pthread_mutex-static.err || true
src/common/runtest.exe -w '' src/functional/pthread_mutex_pi-static.exe >src/functional/pthread_mutex_pi-static.err || true
src/common/runtest.exe -w '' src/functional/pthread_robust-static.exe >src/functional/pthread_robust-static.err || true
src/common/runtest.exe -w '' src/functional/pthread_tsd-static.exe >src/functional/pthread_tsd-static.err || true
src/common/runtest.exe -w '' src/functional/qsort-static.exe >src/functional/qsort-static.err || true
src/common/runtest.exe -w '' src/functional/random-static.exe >src/functional/random-static.err || true
src/common/runtest.exe -w '' src/functional/search_hsearch-static.exe >src/functional/search_hsearch-static.err || true
src/common/runtest.exe -w '' src/functional/search_insque-static.exe >src/functional/search_insque-static.err || true
src/common/runtest.exe -w '' src/functional/search_lsearch-static.exe >src/functional/search_lsearch-static.err || true
src/common/runtest.exe -w '' src/functional/search_tsearch-static.exe >src/functional/search_tsearch-static.err || true
src/common/runtest.exe -w '' src/functional/sem_init-static.exe >src/functional/sem_init-static.err || true
src/common/runtest.exe -w '' src/functional/sem_open-static.exe >src/functional/sem_open-static.err || true
src/common/runtest.exe -w '' src/functional/setjmp-static.exe >src/functional/setjmp-static.err || true
src/common/runtest.exe -w '' src/functional/snprintf-static.exe >src/functional/snprintf-static.err || true
src/common/runtest.exe -w '' src/functional/socket-static.exe >src/functional/socket-static.err || true
src/common/runtest.exe -w '' src/functional/spawn-static.exe >src/functional/spawn-static.err || true
src/common/runtest.exe -w '' src/functional/sscanf-static.exe >src/functional/sscanf-static.err || true
src/common/runtest.exe -w '' src/functional/sscanf_long-static.exe >src/functional/sscanf_long-static.err || true
src/common/runtest.exe -w '' src/functional/stat-static.exe >src/functional/stat-static.err || true
src/common/runtest.exe -w '' src/functional/strftime-static.exe >src/functional/strftime-static.err || true
src/common/runtest.exe -w '' src/functional/string-static.exe >src/functional/string-static.err || true
src/common/runtest.exe -w '' src/functional/string_memcpy-static.exe >src/functional/string_memcpy-static.err || true
src/common/runtest.exe -w '' src/functional/string_memmem-static.exe >src/functional/string_memmem-static.err || true
src/common/runtest.exe -w '' src/functional/string_memset-static.exe >src/functional/string_memset-static.err || true
src/common/runtest.exe -w '' src/functional/string_strchr-static.exe >src/functional/string_strchr-static.err || true
src/common/runtest.exe -w '' src/functional/string_strcspn-static.exe >src/functional/string_strcspn-static.err || true
src/common/runtest.exe -w '' src/functional/string_strstr-static.exe >src/functional/string_strstr-static.err || true
src/common/runtest.exe -w '' src/functional/strptime-static.exe >src/functional/strptime-static.err || true
src/common/runtest.exe -w '' src/functional/strtod-static.exe >src/functional/strtod-static.err || true
src/common/runtest.exe -w '' src/functional/strtod_long-static.exe >src/functional/strtod_long-static.err || true
src/common/runtest.exe -w '' src/functional/strtod_simple-static.exe >src/functional/strtod_simple-static.err || true
src/common/runtest.exe -w '' src/functional/strtof-static.exe >src/functional/strtof-static.err || true
src/common/runtest.exe -w '' src/functional/strtol-static.exe >src/functional/strtol-static.err || true
src/common/runtest.exe -w '' src/functional/strtold-static.exe >src/functional/strtold-static.err || true
src/common/runtest.exe -w '' src/functional/swprintf-static.exe >src/functional/swprintf-static.err || true
src/common/runtest.exe -w '' src/functional/tgmath-static.exe >src/functional/tgmath-static.err || true
src/common/runtest.exe -w '' src/functional/time-static.exe >src/functional/time-static.err || true
src/common/runtest.exe -w '' src/functional/tls_align.exe >src/functional/tls_align.err || true
src/common/runtest.exe -w '' src/functional/tls_init-static.exe >src/functional/tls_init-static.err || true
src/common/runtest.exe -w '' src/functional/tls_local_exec-static.exe >src/functional/tls_local_exec-static.err || true
src/common/runtest.exe -w '' src/functional/udiv-static.exe >src/functional/udiv-static.err || true
src/common/runtest.exe -w '' src/functional/ungetc-static.exe >src/functional/ungetc-static.err || true
src/common/runtest.exe -w '' src/functional/utime-static.exe >src/functional/utime-static.err || true
src/common/runtest.exe -w '' src/functional/vfork-static.exe >src/functional/vfork-static.err || true
src/common/runtest.exe -w '' src/functional/wcsstr-static.exe >src/functional/wcsstr-static.err || true
src/common/runtest.exe -w '' src/functional/wcstol-static.exe >src/functional/wcstol-static.err || true
cat src/math/*.err >src/math/REPORT
cat src/musl/*.err >src/musl/REPORT
src/common/runtest.exe -w '' src/regression/daemon-failure-static.exe >src/regression/daemon-failure-static.err || true
src/common/runtest.exe -w '' src/regression/dn_expand-empty-static.exe >src/regression/dn_expand-empty-static.err || true
src/common/runtest.exe -w '' src/regression/dn_expand-ptr-0-static.exe >src/regression/dn_expand-ptr-0-static.err || true
src/common/runtest.exe -w '' src/regression/execle-env-static.exe >src/regression/execle-env-static.err || true
src/common/runtest.exe -w '' src/regression/fflush-exit-static.exe >src/regression/fflush-exit-static.err || true
src/common/runtest.exe -w '' src/regression/fgets-eof-static.exe >src/regression/fgets-eof-static.err || true
src/common/runtest.exe -w '' src/regression/fgetwc-buffering-static.exe >src/regression/fgetwc-buffering-static.err || true
src/common/runtest.exe -w '' src/regression/flockfile-list-static.exe >src/regression/flockfile-list-static.err || true
src/common/runtest.exe -w '' src/regression/fpclassify-invalid-ld80-static.exe >src/regression/fpclassify-invalid-ld80-static.err || true
src/common/runtest.exe -w '' src/regression/ftello-unflushed-append-static.exe >src/regression/ftello-unflushed-append-static.err || true
src/common/runtest.exe -w '' src/regression/getpwnam_r-crash-static.exe >src/regression/getpwnam_r-crash-static.err || true
src/common/runtest.exe -w '' src/regression/getpwnam_r-errno-static.exe >src/regression/getpwnam_r-errno-static.err || true
src/common/runtest.exe -w '' src/regression/iconv-roundtrips-static.exe >src/regression/iconv-roundtrips-static.err || true
src/common/runtest.exe -w '' src/regression/inet_ntop-v4mapped-static.exe >src/regression/inet_ntop-v4mapped-static.err || true
src/common/runtest.exe -w '' src/regression/inet_pton-empty-last-field-static.exe >src/regression/inet_pton-empty-last-field-static.err || true
src/common/runtest.exe -w '' src/regression/iswspace-null-static.exe >src/regression/iswspace-null-static.err || true
src/common/runtest.exe -w '' src/regression/lrand48-signextend-static.exe >src/regression/lrand48-signextend-static.err || true
src/common/runtest.exe -w '' src/regression/lseek-large-static.exe >src/regression/lseek-large-static.err || true
src/common/runtest.exe -w '' src/regression/malloc-0-static.exe >src/regression/malloc-0-static.err || true
src/common/runtest.exe -w '' src/regression/malloc-brk-fail-static.exe >src/regression/malloc-brk-fail-static.err || true
src/common/runtest.exe -w '' src/regression/malloc-oom-static.exe >src/regression/malloc-oom-static.err || true
src/common/runtest.exe -w '' src/regression/mbsrtowcs-overflow-static.exe >src/regression/mbsrtowcs-overflow-static.err || true
src/common/runtest.exe -w '' src/regression/memmem-oob-read-static.exe >src/regression/memmem-oob-read-static.err || true
src/common/runtest.exe -w '' src/regression/memmem-oob-static.exe >src/regression/memmem-oob-static.err || true
src/common/runtest.exe -w '' src/regression/mkdtemp-failure-static.exe >src/regression/mkdtemp-failure-static.err || true
src/common/runtest.exe -w '' src/regression/mkstemp-failure-static.exe >src/regression/mkstemp-failure-static.err || true
src/common/runtest.exe -w '' src/regression/printf-1e9-oob-static.exe >src/regression/printf-1e9-oob-static.err || true
src/common/runtest.exe -w '' src/regression/printf-fmt-g-round-static.exe >src/regression/printf-fmt-g-round-static.err || true
src/common/runtest.exe -w '' src/regression/printf-fmt-g-zeros-static.exe >src/regression/printf-fmt-g-zeros-static.err || true
src/common/runtest.exe -w '' src/regression/printf-fmt-n-static.exe >src/regression/printf-fmt-n-static.err || true
src/common/runtest.exe -w '' src/regression/pthread-robust-detach-static.exe >src/regression/pthread-robust-detach-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_atfork-errno-clobber-static.exe >src/regression/pthread_atfork-errno-clobber-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_cancel-sem_wait-static.exe >src/regression/pthread_cancel-sem_wait-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_cond-smasher-static.exe >src/regression/pthread_cond-smasher-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_cond_wait-cancel_ignored-static.exe >src/regression/pthread_cond_wait-cancel_ignored-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_condattr_setclock-static.exe >src/regression/pthread_condattr_setclock-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_create-oom-static.exe >src/regression/pthread_create-oom-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_exit-cancel-static.exe >src/regression/pthread_exit-cancel-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_exit-dtor-static.exe >src/regression/pthread_exit-dtor-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_once-deadlock-static.exe >src/regression/pthread_once-deadlock-static.err || true
src/common/runtest.exe -w '' src/regression/pthread_rwlock-ebusy-static.exe >src/regression/pthread_rwlock-ebusy-static.err || true
src/common/runtest.exe -w '' src/regression/putenv-doublefree-static.exe >src/regression/putenv-doublefree-static.err || true
src/common/runtest.exe -w '' src/regression/raise-race-static.exe >src/regression/raise-race-static.err || true
src/common/runtest.exe -w '' src/regression/regex-backref-0-static.exe >src/regression/regex-backref-0-static.err || true
src/common/runtest.exe -w '' src/regression/regex-bracket-icase-static.exe >src/regression/regex-bracket-icase-static.err || true
src/common/runtest.exe -w '' src/regression/regex-ere-backref-static.exe >src/regression/regex-ere-backref-static.err || true
src/common/runtest.exe -w '' src/regression/regex-escaped-high-byte-static.exe >src/regression/regex-escaped-high-byte-static.err || true
src/common/runtest.exe -w '' src/regression/regex-negated-range-static.exe >src/regression/regex-negated-range-static.err || true
src/common/runtest.exe -w '' src/regression/regexec-nosub-static.exe >src/regression/regexec-nosub-static.err || true
src/common/runtest.exe -w '' src/regression/rewind-clear-error-static.exe >src/regression/rewind-clear-error-static.err || true
src/common/runtest.exe -w '' src/regression/rlimit-open-files-static.exe >src/regression/rlimit-open-files-static.err || true
src/common/runtest.exe -w '' src/regression/scanf-bytes-consumed-static.exe >src/regression/scanf-bytes-consumed-static.err || true
src/common/runtest.exe -w '' src/regression/scanf-match-literal-eof-static.exe >src/regression/scanf-match-literal-eof-static.err || true
src/common/runtest.exe -w '' src/regression/scanf-nullbyte-char-static.exe >src/regression/scanf-nullbyte-char-static.err || true
src/common/runtest.exe -w '' src/regression/setenv-oom-static.exe >src/regression/setenv-oom-static.err || true
src/common/runtest.exe -w '' src/regression/setvbuf-unget-static.exe >src/regression/setvbuf-unget-static.err || true
src/common/runtest.exe -w '' src/regression/sigaltstack-static.exe >src/regression/sigaltstack-static.err || true
src/common/runtest.exe -w '' src/regression/sigprocmask-internal-static.exe >src/regression/sigprocmask-internal-static.err || true
src/common/runtest.exe -w '' src/regression/sigreturn-static.exe >src/regression/sigreturn-static.err || true
src/common/runtest.exe -w '' src/regression/sscanf-eof-static.exe >src/regression/sscanf-eof-static.err || true
src/common/runtest.exe -w '' src/regression/statvfs-static.exe >src/regression/statvfs-static.err || true
src/common/runtest.exe -w '' src/regression/strverscmp-static.exe >src/regression/strverscmp-static.err || true
src/common/runtest.exe -w '' src/regression/syscall-sign-extend-static.exe >src/regression/syscall-sign-extend-static.err || true
src/common/runtest.exe -w '' src/regression/uselocale-0-static.exe >src/regression/uselocale-0-static.err || true
src/common/runtest.exe -w '' src/regression/wcsncpy-read-overflow-static.exe >src/regression/wcsncpy-read-overflow-static.err || true
src/common/runtest.exe -w '' src/regression/wcsstr-false-negative-static.exe >src/regression/wcsstr-false-negative-static.err || true
cat src/api/*.err >src/api/REPORT
src/common/runtest.exe -w '' src/functional/tls_align-static.exe >src/functional/tls_align-static.err || true
cat src/regression/*.err >src/regression/REPORT
cat src/functional/*.err >src/functional/REPORT
cat src/api/REPORT src/common/REPORT src/functional/REPORT src/math/REPORT src/musl/REPORT src/regression/REPORT >src/REPORT
grep FAIL src/REPORT || echo PASS

